redis:
  password: "redis_ws1"
  host: "localhost"
  port: 7379
  db: 13
sqlite:
  file_path: ".test-temp/sqlite_test.db"
  url_scheme: "sqlite+aiosqlite"
postgresql:
  password: "pass"
  user: "user"
  host: "host"
  port: 5432
  database: "db"
  url_scheme: "postgresql+asyncpg"
mongodb:
  hosts: ["mongodb1:27017","mongodb2:27017"]
  port: -1
  user: "user"
  password: "password"
  database: "atabas"
  replica_set: "replica_set"
  url_scheme: "mongodb"
elasticsearch:
  host: "https://localhost"
  port: 32096
  username: "user"
  password: "password"
  scheme: "https"
  verify_certs: False
  api_keys:
    study: "key1"
    compound: "key2"
    assignment: "key3"
    assay: "key4"
    sample: "key5"
authentication:
  mtbls_ws2:
    host: "localhost"
    port: 7007
    base_context_path: "/metabolights/ws"
    scheme: http
  standalone:
    application_secret_key: "change_me"
  keycloak:
    realm_name: "metabolights"
    host: "http://localhost/"
    client_id: "client"
    client_secret: "secret"
policy_service:
  opa:
    host_url: "http://localhost:8181"
system_health_check:
  active_health_check_service: standalone
  remote:
    transfer_health_check:
      health_check_url: "http://remote:8081"
  standalone:
    transfer_health_check:
      test: false
      test_response: false
mhd:
  api_key: "mhd_key"
  public_study_base_url: "http://ftp.ebi.ac.uk/pub/databases/metabolights/studies/.test"
  mhd_webservice_base_url: "https://www.metabolomicshub.org/api/submission/v0_1"
mounted_paths:
  private_metadata_files_root_path: "path/metadata-files"
  deleted_private_metadata_files_root_path: "path/deleted-files"
  audit_files_root_path: "pathes/audit-files"
  internal_files_root_path: "path/internal-files"
  deleted_private_data_files_root_path: ""
  private_data_files_root_path: ""
  report_files_root_path: ""
  public_studies_root_path: ""
  deleted_public_studies_root_path: ""
  indices_cache_root_path: "path/cache/indices-data"
run:
  submission:
    port: 7077
    root_path: ""
    logging:
      level: INFO
      selected_formatter: text_formatter
      default_filter_class: mtbls.run.rest_api.submission.log_filter.DefaultLogFilter
  common_worker:
    logging:
      level: INFO
      selected_formatter: text_formatter
      default_filter_class: mtbls.run.worker.common.log_filter.DefaultLogFilter
  monitor:
    port: 5555
  cli:
    logging:
      level: INFO
      selected_formatter: text_formatter
      default_filter_class: mtbls.run.cli.log_filter.DefaultLogFilter
