from typing import Dict, List

from metabolights_utils.models.isa.common import (
    AssayTechnique,
    OrganismAndOrganismPartPair,
)

from mtbls.application.use_cases.indices.kibana_indices.models.common import (
    BaseIsaTableIndexItem,
    IndexValue,
)


class AssayIndexItem(BaseIsaTableIndexItem):
    sample_name: str = ""
    technique: AssayTechnique = AssayTechnique()
    sample: OrganismAndOrganismPartPair = OrganismAndOrganismPartPair()
    files: Dict[str, List[IndexValue]] = {}


ASSAY_FLOAT_VALUE_FIELDS = {
    "Parameter Value[Magnetic field strength]",
    "Parameter Value[Sample pH]",
    "Parameter Value[Temperature]",
    "Parameter Value[Resolving power m/z]",
    "Parameter Value[Resolving power]",
}
ASSAY_INT_VALUE_FIELDS = {
    "Parameter Value[Max count of pixel x]",
    "Parameter Value[Max count of pixel y]",
    "Parameter Value[Pixel size x]",
    "Parameter Value[Pixel size y]",
    "Parameter Value[Number of scans]",
    "Parameter Value[Max dimension x]",
    "Parameter Value[Max dimension y]",
    "Parameter Value[Number of transients]",
}

DEFAULT_ASSAY_COLUMN_NAMES = {
    "Acquisition Parameter Data File",
    "Cryogenic Trap",
    "Data Transformation Name",
    "Derived Spectral Data File",
    "Extract Name",
    "Free Induction Decay Data File",
    "Label",
    "Labeled Extract Name",
    "Metabolite Assignment File",
    "MS Assay Name",
    "NMR Assay Name",
    "Normalization Name",
    "Parameter Value[Autosampler model]",
    "Parameter Value[Cartridge type]",
    "Parameter Value[CE Instrument]",
    "Parameter Value[Chromatography Instrument]",
    "Parameter Value[Column model 1]",
    "Parameter Value[Column model 2]",
    "Parameter Value[Column model]",
    "Parameter Value[Column type 1]",
    "Parameter Value[Column type 2]",
    "Parameter Value[Column type]",
    "Parameter Value[Data file content]",
    "Parameter Value[Data Transformation software version]",
    "Parameter Value[Data Transformation software]",
    "Parameter Value[Derivatization]",
    "Parameter Value[Detector mode]",
    "Parameter Value[Detector]",
    "Parameter Value[DI Instrument]",
    "Parameter Value[Extraction Method]",
    "Parameter Value[FIA Instrument]",
    "Parameter Value[Field of view]",
    "Parameter Value[Guard column]",
    "Parameter Value[High-res image]",
    "Parameter Value[Inlet type]",
    "Parameter Value[Instrument manufacturer]",
    "Parameter Value[Instrument software version]",
    "Parameter Value[Instrument software]",
    "Parameter Value[Instrument]",
    "Parameter Value[Ion source]",
    "Parameter Value[Line scan direction]",
    "Parameter Value[Linescan sequence]",
    "Parameter Value[Localisation pulse sequence name]",
    "Parameter Value[Low-res image]",
    "Parameter Value[Magnetic field strength]",
    "Parameter Value[Magnetic pulse sequence name]",
    "Parameter Value[Mass analyzer]",
    "Parameter Value[Matrix application]",
    "Parameter Value[Matrix]",
    "Parameter Value[Max count of pixel x]",
    "Parameter Value[Max count of pixel y]",
    "Parameter Value[Max dimension x]",
    "Parameter Value[Max dimension y]",
    "Parameter Value[Native spectrum identifier format]",
    "Parameter Value[NMR Probe]",
    "Parameter Value[NMR tube type]",
    "Parameter Value[Number of scans]",
    "Parameter Value[Number of transients]",
    "Parameter Value[Pixel size x]",
    "Parameter Value[Pixel size y]",
    "Parameter Value[Post Extraction]",
    "Parameter Value[Pulse sequence name]",
    "Parameter Value[Raw data file format]",
    "Parameter Value[Resolution]",
    "Parameter Value[Resolving power m/z]",
    "Parameter Value[Resolving power]",
    "Parameter Value[Sample mounting]",
    "Parameter Value[Sample pH]",
    "Parameter Value[Sample preservation]",
    "Parameter Value[Scan m/z range]",
    "Parameter Value[Scan pattern]",
    "Parameter Value[Scan polarity]",
    "Parameter Value[Scan type]",
    "Parameter Value[Section thickness]",
    "Parameter Value[Sectioning instrument]",
    "Parameter Value[Signal range]",
    "Parameter Value[Solvent]",
    "Parameter Value[Spatial resolution]",
    "Parameter Value[SPE-IMS Instrument]",
    "Parameter Value[Spectrum representation]",
    "Parameter Value[Stain]",
    "Parameter Value[Target material]",
    "Parameter Value[Temperature]",
    "Parameter Value[Tissue modification]",
    "Parameter Value[Tomography]",
    "Parameter Value[Voxel size]",
    "Parameter Value[Water inhibition pulse sequence name]",
    "Raw Spectral Data File",
    "Sample Name",
    "Thermal Desorption unit",
}
